[2024-06-04T14:24:23.413+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T14:24:23.425+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: metrics_calculators.run_after_loop manual__2024-06-04T14:24:20.618550+00:00 [queued]>
[2024-06-04T14:24:23.428+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: metrics_calculators.run_after_loop manual__2024-06-04T14:24:20.618550+00:00 [queued]>
[2024-06-04T14:24:23.428+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-04T14:24:23.436+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_after_loop> on 2024-06-04 14:24:20.618550+00:00
[2024-06-04T14:24:23.439+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=13774) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-04T14:24:23.440+0000] {standard_task_runner.py:63} INFO - Started process 13776 to run task
[2024-06-04T14:24:23.440+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'metrics_calculators', 'run_after_loop', 'manual__2024-06-04T14:24:20.618550+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag_reader.py', '--cfg-path', '/tmp/tmpdm9fsmq5']
[2024-06-04T14:24:23.442+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask run_after_loop
[2024-06-04T14:24:23.467+0000] {task_command.py:426} INFO - Running <TaskInstance: metrics_calculators.run_after_loop manual__2024-06-04T14:24:20.618550+00:00 [running]> on host f291404afb14
[2024-06-04T14:24:23.520+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mehdizarria' AIRFLOW_CTX_DAG_ID='metrics_calculators' AIRFLOW_CTX_TASK_ID='run_after_loop' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T14:24:20.618550+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T14:24:20.618550+00:00'
[2024-06-04T14:24:23.521+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T14:24:23.521+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-04T14:24:23.522+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/*** && ls']
[2024-06-04T14:24:23.528+0000] {subprocess.py:86} INFO - Output:
[2024-06-04T14:24:23.530+0000] {subprocess.py:93} INFO - ***.cfg
[2024-06-04T14:24:23.530+0000] {subprocess.py:93} INFO - config
[2024-06-04T14:24:23.530+0000] {subprocess.py:93} INFO - dags
[2024-06-04T14:24:23.531+0000] {subprocess.py:93} INFO - logs
[2024-06-04T14:24:23.531+0000] {subprocess.py:93} INFO - plugins
[2024-06-04T14:24:23.531+0000] {subprocess.py:93} INFO - webserver_config.py
[2024-06-04T14:24:23.531+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-04T14:24:23.531+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T14:24:23.546+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=metrics_calculators, task_id=run_after_loop, run_id=manual__2024-06-04T14:24:20.618550+00:00, execution_date=20240604T142420, start_date=20240604T142423, end_date=20240604T142423
[2024-06-04T14:24:23.586+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-04T14:24:23.597+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-04T14:24:23.598+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
