[2024-06-09T11:36:57.844+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-09T11:36:57.853+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: metrics_calculator.cloud_function_task manual__2024-06-09T11:36:55.645117+00:00 [queued]>
[2024-06-09T11:36:57.857+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: metrics_calculator.cloud_function_task manual__2024-06-09T11:36:55.645117+00:00 [queued]>
[2024-06-09T11:36:57.858+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-09T11:36:57.863+0000] {taskinstance.py:2330} INFO - Executing <Task(CloudFunctionInvokeFunctionOperator): cloud_function_task> on 2024-06-09 11:36:55.645117+00:00
[2024-06-09T11:36:57.867+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=865) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-09T11:36:57.868+0000] {standard_task_runner.py:63} INFO - Started process 866 to run task
[2024-06-09T11:36:57.868+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'metrics_calculator', 'cloud_function_task', 'manual__2024-06-09T11:36:55.645117+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag_reader.py', '--cfg-path', '/tmp/tmph8r371ux']
[2024-06-09T11:36:57.870+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask cloud_function_task
[2024-06-09T11:36:57.900+0000] {task_command.py:426} INFO - Running <TaskInstance: metrics_calculator.cloud_function_task manual__2024-06-09T11:36:55.645117+00:00 [running]> on host d7fa402d9e56
[2024-06-09T11:36:57.947+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mehdizarria' AIRFLOW_CTX_DAG_ID='metrics_calculator' AIRFLOW_CTX_TASK_ID='cloud_function_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T11:36:55.645117+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-09T11:36:55.645117+00:00'
[2024-06-09T11:36:57.948+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-09T11:36:57.960+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-09T11:36:57.963+0000] {base.py:84} INFO - Using connection ID 'gcp_connection' for task execution.
[2024-06-09T11:36:57.963+0000] {functions.py:471} INFO - Calling function function-1.
[2024-06-09T11:37:07.592+0000] {functions.py:478} INFO - Function called successfully. Execution id use2b907zlwy
[2024-06-09T11:37:07.627+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-09T11:37:07.645+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=metrics_calculator, task_id=cloud_function_task, run_id=manual__2024-06-09T11:36:55.645117+00:00, execution_date=20240609T113655, start_date=20240609T113657, end_date=20240609T113707
[2024-06-09T11:37:07.681+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-09T11:37:07.702+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09T11:37:07.703+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
